### ISSUE TITLE
Implement the socket module

### ISSUE THREAD

**Issue by eerimoq** [eerimoq/pumbaa#14]
Useful for the ESP.

**Comment by eerimoq** [comment]
The basic functionality implemented.

**Comment by LupascuAndrei** [comment]
Any chance for the socket.io or websockets modules to be implemented soon ?

**Comment by eerimoq** [comment]
Hi, no, it's not planned. I'm currently working on adding a text editor to be able to easily edit python scripts on the embedded device.
