### ISSUE TITLE
Drivers.exti

### ISSUE THREAD

**Issue by LupascuAndrei** [eerimoq/pumbaa#17]
select example ( https://github.com/eerimoq/pumbaa/blob/master/examples/select/main.py ) crashes on drivers.exti 

how to reproduce : 
>>> import drivers
>>> drivers.Exti

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Exti'

**Comment by eerimoq** [comment]
Which board do you have? The Exti driver is only implemented for Arduino Due and ESP8266, not the ESP32.

**Comment by LupascuAndrei** [comment]
Yes, that makes sense, you are right. 
Thank you.
