### ISSUE TITLE
integrate SSL into arduino boards manager

### ISSUE THREAD

**Issue by LupascuAndrei** [eerimoq/pumbaa#21]
Currently,the latest arduino boards manager version (2.3.2) is not updated with the SSL module
( arduino IDE, board nano32 pumbaa : import ssl -> no module named ssl )

**Comment by eerimoq** [comment]
I'll prepare a release soon, hopefully tonight.

**Comment by LupascuAndrei** [comment]
thank you very much

**Comment by eerimoq** [comment]
Released! =)

Though, I just realized that the select module will not accept ssl sockets. Adding that soon.

**Comment by LupascuAndrei** [comment]
Great, that sure was fast ! thank you very much :D

**Comment by LupascuAndrei** [comment]
Could you,please,give me an ETA on the select module & ssl sockets ? :D 
I've never found true love before working with your project. It's awesome.

**Comment by eerimoq** [comment]
Wow thank you very much =) Glad you like it!

I'll have a look at it this weekend.

**Comment by eerimoq** [comment]
Btw, how did you find out about Pumbaa?

**Comment by LupascuAndrei** [comment]
Searched the internet ( a lot )  for a python module for esp32 and yours seemed the best choice. And so it was, apparently :D

**Comment by eerimoq** [comment]
You can poll the TCP socket instead of the SSL socket. Call the read function on the SSL socket once poll returns.
