### ISSUE TITLE
write directly to flash memory at specific address

### ISSUE THREAD

**Issue by LupascuAndrei** [eerimoq/pumbaa#23]
Is there a way,using your project, to write/read data at specific flash memory address?
thank you very much :D

**Comment by eerimoq** [comment]
It's possible in Simba, but there is no wrapper class implemented in Pumbaa. Can easily be implemented.

**Comment by LupascuAndrei** [comment]
Oh,cool. Can you give me an ETA for this part of the project,please? it's very important for what i'm currently working on atm :D  
Thank you, again, for your quick response

**Comment by eerimoq** [comment]
Implemented the wrapper class. See the documentation here: http://pumbaa.readthedocs.io/en/latest/library-reference/pumbaa/drivers.html#drivers.drivers.Flash

I have experianced instabilities in the flash module from time to time when erasing big chunks of data. Let me know if there is a problem and I'll try to fix it. I'm afraid it will be hard to find the bug...

**Comment by eerimoq** [comment]
Here is a rough description of how OTA/upgrade will work: http://simba-os.readthedocs.io/en/latest/library-reference/oam/upgrade.html

**Comment by LupascuAndrei** [comment]
Thank you very much, it looks great !
I'll be testing both of them as soon as i finish with the exams period. You're great,I didnt expect the flash memory wrapper to be implemented that fast.

**Comment by LupascuAndrei** [comment]
Hello. 
Using your latest pumbaa version, esp32 crashes when trying to import drivers.Flash. 

code : 
>import os
from drivers import Flash

(copy paste from flash_suite.py )
error:  
>Executing frozen module 'main.py'. Traceback (most recent call last): File "main.py", line 7, in <module> ImportError: cannot import name Flash Frozen module 'main.py' exited abnormally.

board : nano32
mcu: esp32
Thank you in advance for your support :D

**Comment by LupascuAndrei** [comment]
[deleted]
never mind,fixed.

**Comment by eerimoq** [comment]
Part of release 2.6.1.
