### ISSUE TITLE
Http server implementation , get post content

### ISSUE THREAD

**Issue by LupascuAndrei** [eerimoq/pumbaa#24]
Using your already implemented http server,is it possible to access "post" data from received requests? If so, how?
I made a workaround by placing the required data in queryparameters,since i have access to the full link requested by a client, but it would be great to be able to get more data from the received http requests. 
**It's not a blocking issue since it can be worked around with query parameters**
Thank you in advance, haven't found any other issues with your project so far. It's great :D

**Comment by eerimoq** [comment]
Ok, so in the latest version of the HTTP server all header fields are part of the request object passed to the request handler function.

POST data can be read in the request handler by calling ``connection.socket_read(request.content_length)``.

Here is an example:

https://github.com/eerimoq/pumbaa/blob/master/examples/http_server/main.py#L45-L60

**Comment by eerimoq** [comment]
Part of release 2.6.1.

**Comment by LupascuAndrei** [comment]
Using your sample code, connection.socket_read( any length ) gets stuck until i cancel the post request from postman
Everything else works fine, i'm able correctly receive GET responses to esp32's https server

**Comment by eerimoq** [comment]
What does the POST request look like in Wireshark?

**Comment by LupascuAndrei** [comment]
i'm currently debugging using osx, i see that wireshark only supports windows/ unix 

here is the post request from postman ( chrome extension ) that i'm using 

POST /test HTTP/1.1
Host: 192.168.4.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Cache-Control: no-cache
Postman-Token: 3c7b8335-1389-ff08-b830-947533bf6c5e

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="var"

val
------WebKitFormBoundary7MA4YWxkTrZu0gW--

esp32 responds correctly to get request ; it gets the correct content_length from the request. connection.socket_read(1) just gets stuck until i close the socket from the osx

**Comment by LupascuAndrei** [comment]
Ok,what i haven't mentioned is that i'm trying to get POST content from the httpS server*.
Sorry, this is the example i'm trying to make it work * 
https://github.com/eerimoq/pumbaa/blob/master/examples/https_server/main.py

**Comment by eerimoq** [comment]
Does it work with non-encrypted HTTP?

**Comment by eerimoq** [comment]
Try changing https://github.com/eerimoq/pumbaa/blob/master/src/module_inet/class_http_server.c#L133 to

```
res = chan_read(self_p->connection_p->chan_p, vstr.buf, size);
```

**Comment by LupascuAndrei** [comment]
changing it to 
res = socket_read( (struct socket_t*) (&self_p->connection_p->chan_p), vstr.buf, size); 
solved the blocking issue, but the actual post data is ignored, all bytes returned are 0

I haven't tested it on non-encrypted HTTP, i'll test it asap, but i don't think there's an issue with the SSL

**Comment by eerimoq** [comment]
It should be chan_read(), not socket_read().

**Comment by eerimoq** [comment]
I pushed a fix for this issue. See 81f93387141b1fa519566ea4863c63baf2d12c42.

**Comment by LupascuAndrei** [comment]
Works like a charm ! Thank you.

**Comment by eerimoq** [comment]
=D
