### ISSUE TITLE
Upgrade http server with ssl

### ISSUE THREAD

**Issue by LupascuAndrei** [eerimoq/pumbaa#26]
Using your implementation of http server & ssl wrapper, is it possible to directly upgrade the http server to https?

**Comment by eerimoq** [comment]
The Simba HTTP server has a function called ``http_server_wrap_ssl()`` that wraps an initialized HTTP server in SSL. Should be easy to add a wrapper in the Pumbaa HTTP server class taking an SSL context object as argument.

https://github.com/eerimoq/simba/blob/master/src/inet/http_server.h#L190-L202

**Comment by eerimoq** [comment]
Implemented! See https://github.com/eerimoq/pumbaa/commit/5493e461e62737acdca18662d27d32d6ee865a94.

Now I just have to create a release... =)

**Comment by eerimoq** [comment]
Part of release 2.6.1.
