### ISSUE TITLE
Bluetooth module 

### ISSUE THREAD

**Issue by LupascuAndrei** [eerimoq/pumbaa#30]
Hello:D 
I've been using your project almost daily and i haven't discoever any other issues. It's working great.
Will the bluetooth module be integrated into pumbaa soon ? I can help by integrating it into pumbaa soon if you're busy these days, but i can't guarantee i'll do it even close to as good as you can.  ( i see it's already implemented into simba )
Thank you very much.

**Comment by eerimoq** [comment]
Hi,
Bluetooth is not implemented in Simba. Where did you see that? The ESP-IDF supports it, but I havn't seen their interface yet so I cannot say if it is easy to wrap in Simba/Pumbaa.

**Comment by LupascuAndrei** [comment]
My mistake, i mistook another implemented module as the bluetooth module, sorry !
