### ISSUE TITLE
How to use remote control peripheral in ESP32 through pumbaa

### ISSUE THREAD

**Issue by mogplus88** [eerimoq/pumbaa#42]
Hi,
I have been trying to use the remote control (RMT) function in ESP32 using C, but was wondering if it was possible to use pumbaa instead? I have played a lot with Zerynth (python) and much prefer Python to C, but it does not support the RMT peripheral, so I was wondering if pumbaa did. I couldn't find anything in the documentation or examples, but maybe I just didn't look hard enough.
Thanks, 
Ian

**Comment by eerimoq** [comment]
Hello,

no, it does not.

/ Erik
